import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    width: '100%',
    position: 'absolute',
    bottom: 0,
    padding: 16,
    zIndex: 120,
  },
  inner: {
    padding: 20,
    backgroundColor: '#141F25',
    borderRadius: 16,
  },
  blastImage: {
    width: 40,
    height: 40,
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 1,
  },
  wrapper: {
    width: '100%',
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    textAlign: 'center',
    fontFamily: 'Atma-SemiBold',
    fontSize: 20,
    color: '#fff',
  },
  text: {
    textAlign: 'center',
    fontFamily: 'Gilroy-Regular',
    fontSize: 14,
    color: '#fff',
  },
  nextBtn: {
    width: 48,
    height: 48,
  },
  nextImg: {
    width: 48,
    height: 48,
    resizeMode: 'contain',
  },
  input: {
    width: '100%',
    height: 112,
    padding: 16,
    marginBottom: 16,
    borderRadius: 16,
    backgroundColor: '#212E36',
    borderColor: '#3A454B',
    borderWidth: 2,
    fontFamily: 'Gilroy-SemiBold',
    fontSize: 18,
    color: '#F0FCFF',
  },
  row: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  rowText: {
    marginRight: 10,
    fontFamily: 'Gilroy-SemiBold',
    fontSize: 18,
    color: '#F0FCFF',
  },
  item: {
    padding: 5,
  },
  button: {
    width: 30,
    height: 30,
    padding: 1,
    borderWidth: 1,
    borderColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  activeButton: {
    width: 30,
    height: 30,
    padding: 1,
    borderWidth: 1,
    borderColor: '#FECE03',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  avatar: {
    width: 68,
    height: 68,
    resizeMode: 'cover',
    borderRadius: 68,
  },
  name: {
    width: '100%',
    marginTop: 10,
    textAlign: 'center',
    fontFamily: 'Gilroy-Regular',
    fontSize: 18,
    color: '#F0FCFF',
  },
  description: {
    textAlign: 'center',
    lineHeight: 18,
    fontFamily: 'Gilroy-Regular',
    fontSize: 14,
    color: '#F0FCFF',
  },
});
